#!/bin/bash
#
# A helper script to download the hg19.fa file

curl ftp://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz --user anonymous -o - | \
gunzip | \
grep -v '^NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$' > data/hg19.fa
