#!/bin/bash
#
# A helper script to download the hg19.fa file and to concatenate all the lines
# belonging to one chromosome into one single line. Multiple N's are replaced by N+

curl ftp://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz --user anonymous -o - | \
gunzip | \
awk '/^>/ { if(set)printf("\n"); else set=1; } !/^>/{ printf("%s",$0); }END{ printf("\n"); }' | \
sed 's/NN*/N+/g' > data/hg19.fa
